/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-107048-ge93006c67b-20220605"
#endif /* AVUTIL_FFVERSION_H */
